### ISSUE TITLE
Auto pop menu - cannot set OFF persistantly

### ISSUE THREAD

**Issue by careca1970** [eexpress/gnome-shell-compare#1]
Hello,
Thanks for the nice and useful extension!

I am on Fedora 35, Gnome 41.3, Xorg.

Now, I can not set the switch "Auto pop menu" persistently at OFF.
I set it once OFF, and at restart it is back ON.
For me, it is not desired to have it popping up on every copy of path or file-name.

Alex

**Comment by eexpress** [comment]
Hi,

Add function of Save all state, upload new verison.
